# Generated by Django 4.2.11 on 2024-04-20 10:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='usermodel',
            options={},
        ),
        migrations.AddField(
            model_name='usermodel',
            name='company_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='usermodel',
            name='company_picture',
            field=models.ImageField(blank=True, null=True, upload_to='company_pictures'),
        ),
        migrations.AlterModelTable(
            name='usermodel',
            table='User',
        ),
    ]
