# Generated by Django 4.2.11 on 2024-04-20 13:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_jobmodel_created_at_jobmodel_is_active_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='jobmodel',
            options={'ordering': ['-created_at']},
        ),
    ]
