# Generated by Django 4.2.11 on 2024-04-20 13:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_alter_jobmodel_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobmodel',
            name='experience',
            field=models.IntegerField(blank=True, choices=[(1, '0-1 year'), (2, '1-2 years'), (3, '2-3 years'), (4, '3-4 years'), (5, '4-5 years')], null=True),
        ),
    ]
