# Generated by Django 4.2.11 on 2024-04-20 17:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_jobmodel_experience'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobmodel',
            name='contact_us',
            field=models.TextField(blank=True, null=True),
        ),
    ]
