# Generated by Django 4.2.11 on 2024-04-20 18:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_applyjobmodel'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='applyjobmodel',
            table='Employee Jobs',
        ),
    ]
