# Generated by Django 4.2.11 on 2024-04-20 18:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0010_alter_applyjobmodel_table'),
    ]

    operations = [
        migrations.AddField(
            model_name='applyjobmodel',
            name='job',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='api.jobmodel'),
        ),
    ]
