# Generated by Django 4.2.11 on 2024-04-20 18:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0011_applyjobmodel_job'),
    ]

    operations = [
        migrations.AlterField(
            model_name='applyjobmodel',
            name='job',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.jobmodel'),
        ),
    ]
