# Generated by Django 4.2.11 on 2024-04-20 20:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0012_alter_applyjobmodel_job'),
    ]

    operations = [
        migrations.AddField(
            model_name='applyjobmodel',
            name='status',
            field=models.IntegerField(blank=True, choices=[(1, 'APPLIED'), (2, 'ACCEPTED'), (3, 'REJECTED')], null=True),
        ),
    ]
