# Generated by Django 4.2.11 on 2024-04-20 20:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0013_applyjobmodel_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='applyjobmodel',
            name='status',
            field=models.IntegerField(choices=[(1, 'APPLIED'), (2, 'ACCEPTED'), (3, 'REJECTED')], default=1),
        ),
    ]
